spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Project_MD4?createDatabaseIfNotExist=true
    username: root
    password: 123456
  #    password: Anhton312
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# jwt
jwt:
  secret_key: rikkei_academy
  expired:
    access: 864000